/**
 * Inter-service notification secrets and API integration configuration.
 */

const NOTIFICATION_SECRETS = {
  CODINET_TRIGGER_SECRET: "codi_sec_trg_192tk596ikg90e9kf9t6b21",
  POLYGON_TRIGGER_SECRET: "poly_sec_trg_89b21f92c3a504d6a7e0892",
  SALESDASH_TRIGGER_SECRET: "sales_sec_trg_78c41f92e2a504d6a7e0891",
};

module.exports = {
  NOTIFICATION_SECRETS,
  CODINET_TRIGGER_SECRET: NOTIFICATION_SECRETS.CODINET_TRIGGER_SECRET,
  POLYGON_TRIGGER_SECRET: NOTIFICATION_SECRETS.POLYGON_TRIGGER_SECRET,
  SALESDASH_TRIGGER_SECRET: NOTIFICATION_SECRETS.SALESDASH_TRIGGER_SECRET,
};
